In [ ]:
# Dependencies:
# faiss-cpu
# sentence-transformers

In [1]:
# import necessary libraries
import pandas as pd

pd.set_option('display.max_colwidth', 100)

In [3]:
df = pd.read_csv('langchain_tutorial/2_news_research_tool_project/notebooks/sample_text.csv')
df.shape

(8, 2)

In [4]:
df

text  \
0                                        Meditation and yoga can improve mental health   
1                     Fruits, whole grains and vegetables helps control blood pressure   
2                                    These are the latest fashion trends for this week   
3                                    Vibrant color jeans for male are becoming a trend   
4                                                   The concert starts at 7 PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel

In [5]:
# Use Hugging Face Sentence Transformers to create embeddings/vectors:
from sentence_transformers import SentenceTransformer

In [6]:
encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

C:\Working\GitHub\sockduct\CIS579\homework4\.venv\Lib\site-packages\huggingface_hub\file_download.py:142: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\james\.cache\huggingface\hub\models--sentence-transformers--all-mpnet-base-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.4k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [7]:
# 8 vectors created - each has 768 elements or features:
vectors.shape

(8, 768)

In [8]:
dim = vectors.shape[1]
dim

768

In [10]:
# Build a FAISS Index for Vectors:
import faiss

# Use Euclidean distance between vectors:
index = faiss.IndexFlatL2(dim)

In [11]:
# Normalize the source vectors (as we are using L2 distance to measure similarity) and add to the index
index.add(vectors)

In [12]:
index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x00000295D2B13F90> >

In [13]:
# Encode search text using same encorder and normalize the output vector
search_query = "I want to buy a polo t-shirt"

# search_query = "looking for places to visit during the holidays"
# search_query = "An apple a day keeps the doctor away"

# Transform search query into a vector:
vec = encoder.encode(search_query)
vec.shape

(768,)

In [15]:
# Convert from one-dimensional array to two-dimensional:
import numpy as np

svec = np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [17]:
index.search(svec, k=2)

# Returns distances (first tuple) and items (second tuple - item 3 and item 2 from original list of 8):

(array([[1.3844836, 1.4039092]], dtype=float32), array([[3, 2]]))

In [19]:
distances, I = index.search(svec, k=2)
I

array([[3, 2]])

In [21]:
# Alternatively:  df.loc[[3, 2]]
df.loc[I[0]]

# Note:  Semantic search - results are most similar to query (fashion in this case):

text category
3  Vibrant color jeans for male are becoming a trend  Fashion
2  These are the latest fashion trends for this week  Fashion

In [28]:
from IPython.display import display

search_query = 'An apple a day keeps the doctor away'
vec = encoder.encode(search_query)
svec = np.array(vec).reshape(1, -1)
D, I = index.search(svec, k=2)
display(D)
df.loc[I[0]]

array([[1.3433158, 1.7125273]], dtype=float32)

text category
1  Fruits, whole grains and vegetables helps control blood pressure   Health
0                     Meditation and yoga can improve mental health   Health

In [29]:
from IPython.display import display

search_query = 'looking for places to visit during the holidays'
vec = encoder.encode(search_query)
svec = np.array(vec).reshape(1, -1)
D, I = index.search(svec, k=2)
display(D)
df.loc[I[0]]

array([[0.9273728, 1.1601746]], dtype=float32)

text  \
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
6   Travel  
7   Travel